feat: support /shorts/ links while extracting youtube video id
awcodes/filament-tiptap-editor pull request #529
Opened 2024-12-23 22:24 UTC by Velka-DEV

Refactored the getEmbedURLFromYoutubeURL in a cleaner way

2024-12-23 22:27 UTC, Velka-DEV commented
Hello @awcodes, may i ask you to review the PR ? Thanks you !

2024-12-28 00:54 UTC, awcodes requested changes
Can you fix all the indentations to match the plugin please?

2024-12-31 15:28 UTC, Velka-DEV commented
> Can you fix all the indentations to match the plugin please?

Thanks you for your review @awcodes. I just pushed a commit to fix the indentations !

2025-01-02 15:28 UTC, awcodes approved these changes

2025-01-02 15:29 UTC, merged